version: '3.5'
services:
  postgresdb:
    image: postgres:alpine
    restart: always
    container_name: "postgresdb"
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_DB=employee
      - POSTGRES_HOST=postgresdb
      - POSTGRES_PASSWORD=hrhk
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432


  web:
    build: ./
    links:
      - postgresdb
    container_name: crud-service
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb